### ISSUE TITLE
Manual Light Mode Possible?

### ISSUE THREAD

**Issue by ericjanto** [linuz90/better-roam-research#24]
Hi, love this theme!

I was just wondering if it was possible to enable the light mode despite having my Mac set on dark mode?

**Comment by linuz90** [comment]
Thanks! Unfortunately not at this moment, I'm using the CSS native `prefers-color-scheme` query. I'll look into ways of doing this.

**Comment by hanct** [comment]
> Hi, love this theme!
> 
> I was just wondering if it was possible to enable the light mode despite having my Mac set on dark mode?

Me too.  wanted to have my PC set to white mode, with the roam set to dark mode

**Comment by linuz90** [comment]
I have an idea on how to implement this, so I'm re-opening this issue and I'll give it a shot soon.

**Comment by devinmancuso** [comment]
+1 was looking for this feature, would be extremely useful! Thanks for reopening this one @linuz90

**Comment by jabossu** [comment]
I'm looking for the opposite : setting roam to dark mode while having my browser set to light.
In fact, my browser isn't set to anything : i'm running linux, which doesn't have a system wide dark/light mode system.

Thanks for the gorgeous theme !

**Comment by linuz90** [comment]
Just added support to this.

In your `roam/css`, instead of `main.css`, import `dark.css` or `light.css` to force the respective theme.

To achieve these I've used sass imports, so that `main.scss` imports both theme and leverages the system preference, while `dark.scss` and `light.scss` only import the respective palette.

Enjoy!
